### PR TITLE
[ETL-463] Add stack for study gxvwhj

### PR DESCRIPTION
**Pull request by philerooski**

### CODE REVIEW

**Review by thomasyu888 — CHANGES_REQUESTED** [review]
Do you need to add in the cronjob?

**Review by thomasyu888 — APPROVED** [review]
🔥 nice! Going to pre-approve, but just to confirm, from now on, we will not be using shared_metadataschema right?

**Comment by philerooski** [comment]
@thomasyu888 I think you mean `sharedSchema`. Only these ICAR assessments use the self-referencing format so far. So for studies which only use ICAR assessments they won't have a `sharedSchema` dataset. But all other assessments thus far use `sharedSchema` and studies which include them will have a `sharedSchema` dataset.

**Comment by thomasyu888** [comment]
Ah yes @philerooski, that is what I meant. Thanks!

**Pull request merged**
